name: "Test"
on: ["push", "pull_request"]

jobs:
  test_and_build:
    name: "Compile & Lint"
    runs-on: "ubuntu-latest"
    steps:
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: latest
        elixir-version: latest

    - uses: actions/checkout@v1
    - run: |
        mix deps.get
        mix lint
        mix test
